### ISSUE TITLE
Problem with trailing \n characters

### ISSUE THREAD

**Issue by JeffJerseyCow** [cs01/pygdbmi#30]
Sometimes gdb return the characters \n...not as a new line but escapes the \\
e.g. \\\n not \n

An error is thrown when writing the following command:

### gdb_mi_text --- =tsv-created,name="trace_timestamp",initial="0"\n

The \n is with the escaped \ and attempts to parse a string of length 0 within **_parse_val** thus throwing an unexpected character exception.

I've written a patch that searches for the characters at the end of each string to parse and removes them.

https://pastebin.com/gfuUiD8Z

I'm unsure where you want to issue a fix so haven't created a pull request.

**Comment by JeffJerseyCow** [comment]
### Crash Dump
Traceback (most recent call last):
  File "/home/chris/code/python/fuzzle/fuzzle/duzzle/__main__.py", line 42, in <module>
    sys.exit(main())
  File "/home/chris/code/python/fuzzle/fuzzle/duzzle/__main__.py", line 33, in main
    resp = d.write('-target-select remote {}:{}'.format(address, port))
  File "/home/chris/code/python/fuzzle/fuzzle/duzzle/core/context.py", line 44, in write
    resp = self._controller.get_gdb_response(timeout_sec=1, raise_error_on_timeout=False)
  File "/home/chris/.virtualenvs/avatar/lib/python3.6/site-packages/pygdbmi/gdbcontroller.py", line 217, in get_gdb_response
    retval = self._get_responses_unix(timeout_sec, verbose)
  File "/home/chris/.virtualenvs/avatar/lib/python3.6/site-packages/pygdbmi/gdbcontroller.py", line 278, in _get_responses_unix
    responses_list = self._get_responses_list(raw_output, stream, verbose)
  File "/home/chris/.virtualenvs/avatar/lib/python3.6/site-packages/pygdbmi/gdbcontroller.py", line 317, in _get_responses_list
    parsed_response = gdbmiparser.parse_response(response)
  File "/home/chris/.virtualenvs/avatar/lib/python3.6/site-packages/pygdbmi/gdbmiparser.py", line 41, in parse_response
    token, message, payload = _get_notify_msg_and_payload(gdb_mi_text, stream)
  File "/home/chris/.virtualenvs/avatar/lib/python3.6/site-packages/pygdbmi/gdbmiparser.py", line 164, in _get_notify_msg_and_payload
    payload = _parse_dict(stream)
  File "/home/chris/.virtualenvs/avatar/lib/python3.6/site-packages/pygdbmi/gdbmiparser.py", line 205, in _parse_dict
    key, val = _parse_key_val(stream)
  File "/home/chris/.virtualenvs/avatar/lib/python3.6/site-packages/pygdbmi/gdbmiparser.py", line 239, in _parse_key_val
    val = _parse_val(stream)
  File "/home/chris/.virtualenvs/avatar/lib/python3.6/site-packages/pygdbmi/gdbmiparser.py", line 287, in _parse_val
    raise ValueError('unexpected character: %s' % (c))
ValueError: unexpected character:

**Comment by cs01** [comment]
Thanks for reporting this. I added a fix in 0.8.1.1 that removes unexpected text after parsing a value, as well as unit tests.
